version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: projetfinal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    ports:
      - "3002:3001"
    depends_on:
      - db
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./mon-projet-react
    ports:
      - "443:443"   # HTTPS
    depends_on:
      - backend

volumes:
  postgres_data:
